### ISSUE TITLE
can't save and can't reopen script

### ISSUE THREAD

**Issue by acormier** [Tsunami-ide/public#11]
If I edit a script in Tsunami I can't save it.

If I close and try to reopen a script it doesn't open.

environment:
Rhino 5 (32bit)
Windows 8

**Comment by moloneymb** [comment]
G'day Alain,

Thanks for reporting. Both are known issues.

The compiler was hooked up to a code / snippet server with push functionality for synchronization and state management but that was not complete for the release so the hooks were removed along with the save function and the ability to re-open files. 

We will add the hooks back in for both of these functions in the next release.

**Comment by moloneymb** [comment]
Fixed
