### ISSUE TITLE
Can't load ExcelFSharp.vsto

### ISSUE THREAD

**Issue by ovatsus** [Tsunami-ide/public#13]
I get this error:

---
## Visual Studio Tools for Office Solution Installer

The following Microsoft Office solution cannot be loaded because a compatible version of the .NET Framework is not installed: ExcelFSharp.vsto
## OK   

I have Excel 2010 and .NET 4.5 installed

**Comment by moloneymb** [comment]
G'day Gustavo - do you have the VSTO runtime installed? Despite what the error says it's not the framework version.

**Comment by ovatsus** [comment]
Turns out I had the wrong version of VSTO installed, after fixing that it now works fine
