### ISSUE TITLE
canot load Tsunami for Rhino

### ISSUE THREAD

**Issue by goswinr** [Tsunami-ide/public#15]
System::AppDomain::CurrentDomain->UnhandledException event occured

SENDER: Name:DefaultDomain
Keine Kontextrichtlinien vorhanden.
Hi Matt, 
my Rhino is crashing when trying to load Tsunami because of a registry that can not be accessed without admin rights.
my version is from the 16 feb. ( its not the latest one).
shall I post bugs here, via email or on the google group?
 thanks Goswin

EXCEPTION: System.UnauthorizedAccessException
MESSAGE: Der Zugriff auf den Registrierungsschlüssel "HKEY_LOCAL_MACHINE\Software\Earthquake Enterprises\Tsunami" wurde verweigert.
SOURCE: FSharp.Core
CALL STACK
   bei Microsoft.FSharp.Control.CancellationTokenOps.Start@1201-1.Invoke(Exception e)
   bei <StartupCode$FSharp-Core>.$Control.loop@428-40(Trampoline this, FSharpFunc`2 action)
   bei Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction)
   bei Microsoft.FSharp.Control.TrampolineHolder.Protect(FSharpFunc`2 firstAction)
   bei <StartupCode$FSharp-Core>.$Control.-ctor@485-1.Invoke(Object state)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   bei System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by moloneymb** [comment]
G'day, closed by accident. This initial release does not support embedding. We're working on it.
