### ISSUE TITLE
This is a common Windows 8 UI problem

### ISSUE THREAD

**Issue by jackfoxy** [Tsunami-ide/public#19]
On a multi-monitor Windows8 system using a high contrast theme, dragging the Tsunami window from one monitor to another results in vertical black bars. The bars go away upon any resizing action on the window.

This problem seems to be endemic to Windows 8 apps. 

I reported this to MS about Visual Studio 2012, and their workaround is "go to Tools\Options\, and disable 'Hardware Acceleration'". I hope that gives you a clue how to fix this.

**Comment by moloneymb** [comment]
G'day Jack, this sounds like an operating system issue. It's a shame really. 

Try running this in the built in FSI 

#r "PresentationCore.dll"
#r "WindowsBase.dll"
System.Windows.Media.RenderOptions.ProcessRenderMode <- System.Windows.Interop.RenderMode.SoftwareOnly

If it works you can add it to the initialization script or create a plugin. The initialization script is in the user directory/Tsunami/init.fsx

**Comment by jackfoxy** [comment]
Brilliant! That fixes it. I have reported this to MS, but they closed the issue after giving me the workaround for VS2012. Maybe it will be fixed in Win8.1
